version: '2'
services:
  locust_master:
      build: .
      image: sentinel/sentinel-locust:latest
      links:
          - influxdb
          - statsd
          - grafana
      ports:
          - "8089:8089"
          - "5000:5000"
#      volumes:
#          - ./additionalmonitoring/grafana/dashboard.json:/src/app/dashboard.json
      working_dir: /src/app
      environment:
          STATSD_HOST: statsd
          STATSD_PORT: 8125
          STATSD_PREFIX: locust
          GRAFANA_URL: http://grafana:3000
          GRAFANA_USER: admin
          GRAFANA_PASSWORD: admin
          INFLUXDB_USER: root
          INFLUXDB_PASSWORD: root
          INFLUXDB_HOST: http://influxdb:8086
          LOCUST_MODE: master
          SCENARIO_FILE: locusts.py
          TARGET_HOST: ${TARGET_HOST}
          EXTRA_MONITORING: "True"
          LOCUSTS: RDLocust
  locust_node:
      build: .
      image: sentinel/sentinel-locust:latest
      links:
          - influxdb
          - statsd
          - grafana
#      volumes:
#          - ./additionalmonitoring/grafana/dashboard.json:/src/app/dashboard.json
      working_dir: /src/app
      environment:
          STATSD_HOST: statsd
          STATSD_PORT: 8125
          STATSD_PREFIX: locust
          GRAFANA_URL: http://grafana:3000
          GRAFANA_USER: admin
          GRAFANA_PASSWORD: admin
          INFLUXDB_USER: root
          INFLUXDB_PASSWORD: root
          INFLUXDB_HOST: http://influxdb:8086
          LOCUST_MODE: worker
          SCENARIO_FILE: locusts.py
          TARGET_HOST: ${TARGET_HOST}
          LOCUST_MASTER: locust_master
          EXTRA_MONITORING: "True"
          LOCUSTS: RDLocust
  statsd:
      image: shakr/statsd-influxdb
      ports:
          - "8126:8126"
          - "8125:8125/tcp"
          - "8125:8125/udp"
      environment:
          INFLUXDB_HOST: influxdb
          INFLUXDB_DATABASE: statsd
          INFLUXDB_USERNAME: root
          INFLUXDB_PASSWORD: root
      volumes:
          - ./additionalmonitoring/statsd/statsd-config.js:/statsd/config.js
      links:
          - influxdb
  influxdb:
      image: tutum/influxdb:0.8.8
      ports:
          - "8083:8083"
          - "8086:8086"
      environment:
          PRE_CREATE_DB: statsd
  grafana:
      image: grafana/grafana:2.0.1
      ports:
          - "3000:3000"
      links:
          - influxdb
