apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: statsd
  name: statsd
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: statsd
    spec:
      containers:
      - env:
        - name: INFLUXDB_DATABASE
          value: statsd
        - name: INFLUXDB_HOST
          value: influxdb
        - name: INFLUXDB_PASSWORD
          value: root
        - name: INFLUXDB_USERNAME
          value: root
        image: eu.gcr.io/kube-perf/statsd-influxdb
        name: statsd
        ports:
        - containerPort: 8126
        - containerPort: 8125
        - containerPort: 8125
          protocol: UDP
        resources: {}
#        volumeMounts:
#        - mountPath: /statsd/config.js
#          name: statsd-claim0
      restartPolicy: Always
#      volumes:
#      - name: statsd-claim0
#        persistentVolumeClaim:
#          claimName: statsd-claim0
status: {}
